# 1. DEPLOYMENT BLUE (v1.0)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duoc-app-blue
  labels:
    app: duoc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duoc-app
      version: blue
  template:
    metadata:
      labels:
        app: duoc-app
        version: blue
    spec:
      containers:
      - name: node-app-container
        # Cambiado de $ECR_URI_V1 a imagen real
        image: nginx:1.25
        ports:
        - containerPort: 3000
        imagePullPolicy: Always

---
# 2. SERVICE (LoadBalancer)
apiVersion: v1
kind: Service
metadata:
  name: duoc-app-bg-service
spec:
  selector:
    # Este es el selector que el pipeline cambiará de 'blue' a 'green'
    app: duoc-app
    version: blue 
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 3000

---
# 3. DEPLOYMENT GREEN (v2.0)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: duoc-app-green
  labels:
    app: duoc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: duoc-app
      version: green
  template:
    metadata:
      labels:
        app: duoc-app
        version: green
    spec:
      containers:
      - name: node-app-container
        # Cambiado de $ECR_URI_V2 a imagen real (un tag distinto para notar el cambio)
        image: nginx:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
