name: Despliegue EKS - Estrategias de Rollout

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      strategy:
        description: 'Estrategia a Ejecutar'
        required: true
        type: string
        default: 'rolling-update'
      eks_cluster_name:
        description: 'Nombre del Cluster EKS'
        required: true
        default: 'duoc-eks-cluster-cli'
      aws_region:
        description: 'Región de AWS'
        required: true
        default: 'us-east-1'

env:
  # Cumplimos con la directiva de GitHub para 2026
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  # IMPORTANTE: Estos valores aseguran que el PUSH no de Exit Code 254
  DEF_REGION: 'us-east-1'
  DEF_CLUSTER: 'duoc-eks-cluster-cli'

jobs:
  deploy-strategy:
    runs-on: ubuntu-latest
    permissions:
      contents: read 
    
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ github.event.inputs.aws_region || env.DEF_REGION }}

      - name: Configurar acceso a EKS (kubeconfig)
        run: |
          CLUSTER="${{ github.event.inputs.eks_cluster_name || env.DEF_CLUSTER }}"
          REGION="${{ github.event.inputs.aws_region || env.DEF_REGION }}"
          aws eks update-kubeconfig --name "$CLUSTER" --region "$REGION"

      # El resto de tus pasos (Rolling, Recreate, etc.) se mantienen igual...
